### ISSUE TITLE
Does not seem to work with static tableviews (scroll problems )

### ISSUE THREAD

**Issue by ghost** [problame/CSNotificationView#13]
Once a CSNotification is shown from a UITableViewController with static cells, tableview can no longer scroll to the bottom: scrolling bounces back and hides the bottom cells (as though its content size or frame is incorrenct). Scrolling works as expected until CSNotification is first called from the view controller.
Tableviews with dynamic cells seems to work properly.

**Comment by Ewg777** [comment]
#74
