### ISSUE TITLE
Error: -[NSBundle initWithURL:]: nil URL argument

### ISSUE THREAD

**Issue by Jeehut** [problame/CSNotificationView#46]
There's currently a problem with finding the right bundle when getting the images in `imageForStyle`. My app crashed due to the error mentioned in the title.

I'm using XCode 6.1 GM release.

**Comment by bluwave** [comment]
I got the same error as @fdddf using objc.  @Dschee fix actually fixed it just fine using cocoapods.

**Comment by bluwave** [comment]
In my case I think what was effecting the "copy pods resources" not to work is that I have multiple projects.  So that build phase was never install on pod install or pod update.  So I added a new run script phase to my main project UI target 

`"${SRCROOT}/../Pods/Target Support Files/Pods-<TargetName>/Pods-<TargetName>-resources.sh"`

This seemed to fix it.

**Comment by hitendradeveloper** [comment]
IF you are not using cocoaPods, 
replace + (UIImage*)imageForStyle:(CSNotificationViewStyle)style in CSNotificationView.m
as below.

+ (UIImage*)imageForStyle:(CSNotificationViewStyle)style
{
    UIImage* matchedImage = nil;
    switch (style) {
        case CSNotificationViewStyleSuccess:
            matchedImage = [UIImage imageNamed:@"checkmark"];
            break;
        case CSNotificationViewStyleError:
            matchedImage = [UIImage imageNamed:@"exclamationMark"];
            break;
        default:
            break;
    }
    return matchedImage;
}

**Comment by meet2ns** [comment]
For issues related to pod resources ,If you dont want to use pods,copy the images in your project and set the image accordingly.As shown in example
- (UIImage_)imageForStyle:(CSNotificationViewStyle)style
  {
  UIImage_ matchedImage = nil;
  
  // Either main bundle or framework bundle.
  //NSBundle *containerBundle = [NSBundle bundleForClass:CSNotificationView.class];
  
  // CSNotificationView.bundle is generated by CocoaPods using `resource_bundle` in Podspec.
  //  NSBundle *assetsBundle = [NSBundle bundleWithURL:[containerBundle URLForResource:@"CSNotificationView" withExtension:@"bundle"]];
  
    switch (style) {
        case CSNotificationViewStyleSuccess:
            matchedImage = [UIImage imageNamed:@"checkmark"];;
            break;
        case CSNotificationViewStyleError:
            matchedImage = [UIImage imageNamed:@"exclamationMark"] ;
            break;
        default:
            break;
    }
    return matchedImage;
  }

**Comment by mabedMRD** [comment]
as @hitendradeveloper  said, make sure that your resources folder is in project

thanks @hitendradeveloper you helped me
