### ISSUE TITLE
NavigationController with navigationBarHidden

### ISSUE THREAD

**Issue by xzysun** [problame/CSNotificationView#58]
When used in a NavigationController-based views, if the navigation bar is hidden, the notification view is present over the status bar, and this may caused to be rejected by apple.

**Comment by problame** [comment]
Hello @xzysun, so far, I have not heard about any rejections caused by `CSNotificationView`.

There is code handling the `navigationBar`-hidden state. Could you provide sample code documenting the issue?

**Comment by xzysun** [comment]
@problame  In my case, I have a view controller hide navigationbar when appear. The itunes review said that "your application places an overlay on top of the status bar". I think that when navigationbar is hidden, the CSNotificationView comes down and made the status bar change color, and this situation may be against with Apple Interface Guidelines.

**Comment by problame** [comment]
CSNotificationView is never presented on top of the status bar.
You can check its behavior with a hidden navigation bar by hiding it in the Root View Controller of the demo project:

``` objc
@implementation CSRootViewController

- (void)viewWillAppear:(BOOL)animated
{
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}
```

The demo project also includes other examples on how to use CSNotificationView.
